//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practa5laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int ID_Delivery { get; set; }
        public int ID_Zakaz { get; set; }
        public int ID_Sotrudnik { get; set; }
        public string AddressD { get; set; }
        public string DataD { get; set; }
        public string TimeD { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
