//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practa5laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalOrder
    {
        public int ID_FinalOrder { get; set; }
        public int ID_Zakaz { get; set; }
        public Nullable<decimal> Summa { get; set; }
    
        public virtual Zakaz Zakaz { get; set; }
    }
}
