//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practa5laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShourumContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShourumContent()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int ID_ShourumContent { get; set; }
        public int ID_Shourum { get; set; }
        public int ID_Furniture { get; set; }
        public int Kolichestvo { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual Shourum Shourum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
